Math magicians: full website
SamanAtashi/mathmagician pull request #5
Opened 2021-10-25 08:16 UTC by SamanAtashi

# Math magicians: full website
Features introduced are as follows:
- React routers
- styling components using basic styling
- Added Pages : `Home` , `Calculator` , `Quote`

2021-10-25 08:28 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-25 08:28 UTC, arslanbisharat commented on src/App.js
> +          <Calculator />
- [ ] The Calculator is not working properly. Please have a look at the Gif below to know what is happening. 
![1](https://user-images.githubusercontent.com/58504655/138661189-619a0cde-7f57-4b5b-9910-6e2132460852.gif)

2021-10-25 08:28 UTC, arslanbisharat commented on src/index.css
> +
- [ ] [Optional] Let's add a live demo link in your Readme.

2021-10-26 11:31 UTC, mke2111 approved these changes
### Hi @SamanAtashi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-26 11:33 UTC, merged